modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="FlamingIzanagi"
logoFile="icon.png"
logoBlur=false
description='''Client-side mod that sends a defined signal to the server proxy plugin, which automatically redirects the player to the modded server. This helps avoid problems in your lobby and avoids creating instances outside the security of your proxy.'''
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
